apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Release.Name }}-job"
  namespace: "{{ .Values.namespace }}"
  labels:
    experimentId: "{{ .Values.experimentId }}"
spec:
  template:
    spec:
      containers:
      - name: "{{ .Release.Name }}-worker-python"
        image: "{{ .Values.images.python }}"
        env:
        - name: 'EXPERIMENT_ID'
          value: "{{ .Values.experimentId }}"
        - name: 'WORK_QUEUE'
          value: "{{ .Values.workQueueName }}"
        - name: 'K8S_ENV'
          value: "{{ .Values.clusterEnv }}"
        volumeMounts:
        - name: 'data'
          mountPath: '/data'
      - name: "{{ .Release.Name }}-worker-r"
        image: "{{ .Values.images.r }}"
        volumeMounts:
        - name: 'data'
          mountPath: '/data'
        ports:
        - containerPort: 4000
      volumes:
      - name: 'data'
        persistentVolumeClaim:
          claimName: "{{ .Release.Name }}-pvc"
      restartPolicy: OnFailure
      serviceAccountName: 'deployment-runner'