stages:
    - build
    - test
    - deploy  # dummy stage to follow the template guidelines
    - review
    - dast
    - staging
    - canary
    - production
    - incremental rollout 10%
    - incremental rollout 25%
    - incremental rollout 50%
    - incremental rollout 100%
    - performance
    - cleanup
  
variables:
    ROLLOUT_RESOURCE_TYPE: pod
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""
    STAGING_ENABLED: "true"
    K8S_SECRET_AWS_DEFAULT_REGION: "eu-west-2"

include:
    - template: Jobs/Build.gitlab-ci.yml
    - template: Jobs/Deploy.gitlab-ci.yml