stages:
    - build
    - test
    - deploy  # dummy stage to follow the template guidelines
    - review
    - dast
    - staging
    - canary
    - production
    - incremental rollout 10%
    - incremental rollout 25%
    - incremental rollout 50%
    - incremental rollout 100%
    - performance
    - cleanup
  
variables:
    ROLLOUT_STATUS_DISABLED: "true"
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""
    STAGING_ENABLED: "true"
    K8S_SECRET_AWS_DEFAULT_REGION: "eu-west-2"
    HELM_UPGRADE_EXTRA_ARGS: "--cleanup-on-fail --set gitlab_deploy_user=${GITLAB_DEPLOY_USER} --set gitlab_deploy_password=${GITLAB_DEPLOY_PASSWORD} --set gitlab_registry_url=${CI_REGISTRY}"

test:
    stage: test
    image: gliderlabs/herokuish:latest
    needs: []
    script:
        - pip3 install -r requirements.txt
        - cd src/
        - python3 -m pytest --cov=.
    rules:
        - if: '$TEST_DISABLED'
          when: never
        - if: '$CI_COMMIT_TAG || $CI_COMMIT_BRANCH'

include:
    - template: Jobs/Build.gitlab-ci.yml
    - template: Jobs/Deploy.gitlab-ci.yml