apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: can-create-jobs
rules:
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: api-can-spawn-workers
  namespace: {{.Release.Namespace}}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: can-create-jobs
subjects:
- kind: ServiceAccount
  name: default
  namespace: api-18445709-{{ template "trackableappname" . }}

